parser: "@typescript-eslint/parser"

parserOptions:
  ecmaVersion: latest
  project: tsconfig.json

env:
  node: true
  browser: true

extends:
  - airbnb-typescript
  - airbnb/hooks
  - plugin:@typescript-eslint/recommended
  - plugin:prettier/recommended
  - plugin:@tanstack/eslint-plugin-query/recommended

plugins:
  - react
  - import
  - tanstack/query
  - tanstack/eslint-plugin-query

rules:
  prettier/prettier: warn
  no-console: off
  "@typescript-eslint/no-unused-vars": warn
  "react-hooks/exhaustive-deps": off
  "@typescript-eslint/no-explicit-any": off # TODO: remove this when the connection to the backend is done
  "@tanstack/query/exhaustive-deps": "error"
  "@tanstack/query/stable-query-client": "error"
