root: true

env:
  browser: true
  es2020: true

extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:react-hooks/recommended
  - plugin:react-hooks/recommended
  - airbnb-typescript
  - airbnb/hooks
  - plugin:prettier/recommended
  - plugin:import/recommended

ignorePatterns:
  - 'dist'
  - .eslintrc.yaml

parser: '@typescript-eslint/parser'

parserOptions:
  ecmaVersion: latest
  project: tsconfig.json

plugins:
  - 'react-refresh'

rules:
  react-refresh/only-export-components:
    - 'warn'
    - allowConstantExport: true
  prettier/prettier: "warn"
  no-console: "off"
