version: "3"

services:
  server:
    build: ./server
    container_name: server
    # platform: linux/amd64
    restart: on-failure
    ports:
      - "8080:8080"
    volumes:
      - ./server:/usr/app/server/

  client_web:
    build: ./client_web
    container_name: client_web
    # platform: linux/amd64
    restart: on-failure
    ports:
      - "8082:8082"
    volumes:
      - ./client_web:/usr/app/client_web/
      - /usr/app/client_web/node_modules
